name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Assemble with Gradle
      run: ./gradlew assembleDebug

    - name: Upload apk
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: app-debug.apk
        path: ./app/build/outputs/apk/debug/app-debug.apk